// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.
// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

#ifndef  GOOGLE_ANDROIDPUBLISHER_API_ANDROIDPUBLISHER_API_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_ANDROIDPUBLISHER_API_H_

#include "google/androidpublisher_api/apk_binary.h"
#include "google/androidpublisher_api/apk.h"
#include "google/androidpublisher_api/apk_listing.h"
#include "google/androidpublisher_api/apk_listings_list_response.h"
#include "google/androidpublisher_api/externally_hosted_apk_uses_permission.h"
#include "google/androidpublisher_api/externally_hosted_apk.h"
#include "google/androidpublisher_api/apks_add_externally_hosted_request.h"
#include "google/androidpublisher_api/apks_add_externally_hosted_response.h"
#include "google/androidpublisher_api/apks_list_response.h"
#include "google/androidpublisher_api/app_details.h"
#include "google/androidpublisher_api/app_edit.h"
#include "google/androidpublisher_api/timestamp.h"
#include "google/androidpublisher_api/developer_comment.h"
#include "google/androidpublisher_api/device_metadata.h"
#include "google/androidpublisher_api/user_comment.h"
#include "google/androidpublisher_api/comment.h"
#include "google/androidpublisher_api/deobfuscation_file.h"
#include "google/androidpublisher_api/deobfuscation_files_upload_response.h"
#include "google/androidpublisher_api/entitlement.h"
#include "google/androidpublisher_api/page_info.h"
#include "google/androidpublisher_api/token_pagination.h"
#include "google/androidpublisher_api/entitlements_list_response.h"
#include "google/androidpublisher_api/expansion_file.h"
#include "google/androidpublisher_api/expansion_files_upload_response.h"
#include "google/androidpublisher_api/image.h"
#include "google/androidpublisher_api/images_delete_all_response.h"
#include "google/androidpublisher_api/images_list_response.h"
#include "google/androidpublisher_api/images_upload_response.h"
#include "google/androidpublisher_api/price.h"
#include "google/androidpublisher_api/in_app_product_listing.h"
#include "google/androidpublisher_api/month_day.h"
#include "google/androidpublisher_api/prorate.h"
#include "google/androidpublisher_api/season.h"
#include "google/androidpublisher_api/in_app_product.h"
#include "google/androidpublisher_api/inappproducts_insert_request.h"
#include "google/androidpublisher_api/inappproducts_update_request.h"
#include "google/androidpublisher_api/inappproducts_batch_request_entry.h"
#include "google/androidpublisher_api/inappproducts_batch_request.h"
#include "google/androidpublisher_api/inappproducts_insert_response.h"
#include "google/androidpublisher_api/inappproducts_update_response.h"
#include "google/androidpublisher_api/inappproducts_batch_response_entry.h"
#include "google/androidpublisher_api/inappproducts_batch_response.h"
#include "google/androidpublisher_api/inappproducts_list_response.h"
#include "google/androidpublisher_api/listing.h"
#include "google/androidpublisher_api/listings_list_response.h"
#include "google/androidpublisher_api/product_purchase.h"
#include "google/androidpublisher_api/review.h"
#include "google/androidpublisher_api/review_reply_result.h"
#include "google/androidpublisher_api/reviews_list_response.h"
#include "google/androidpublisher_api/reviews_reply_request.h"
#include "google/androidpublisher_api/reviews_reply_response.h"
#include "google/androidpublisher_api/subscription_deferral_info.h"
#include "google/androidpublisher_api/subscription_purchase.h"
#include "google/androidpublisher_api/subscription_purchases_defer_request.h"
#include "google/androidpublisher_api/subscription_purchases_defer_response.h"
#include "google/androidpublisher_api/testers.h"
#include "google/androidpublisher_api/track.h"
#include "google/androidpublisher_api/tracks_list_response.h"
#include "google/androidpublisher_api/voided_purchase.h"
#include "google/androidpublisher_api/voided_purchases_list_response.h"

#include "google/androidpublisher_api/android_publisher_service.h"


#endif  // GOOGLE_ANDROIDPUBLISHER_API_ANDROIDPUBLISHER_API_H_
