// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_APK_LISTING_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_APK_LISTING_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class ApkListing : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static ApkListing* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ApkListing(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ApkListing(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~ApkListing();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::ApkListing</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::ApkListing");
  }

  /**
   * Determine if the '<code>language</code>' attribute was set.
   *
   * @return true if the '<code>language</code>' attribute was set.
   */
  bool has_language() const {
    return Storage().isMember("language");
  }

  /**
   * Clears the '<code>language</code>' attribute.
   */
  void clear_language() {
    MutableStorage()->removeMember("language");
  }


  /**
   * Get the value of the '<code>language</code>' attribute.
   */
  const StringPiece get_language() const {
    const Json::Value& v = Storage("language");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>language</code>' attribute.
   *
   * The language code, in BCP 47 format (eg "en-US").
   *
   * @param[in] value The new value.
   */
  void set_language(const StringPiece& value) {
    *MutableStorage("language") = value.data();
  }

  /**
   * Determine if the '<code>recentChanges</code>' attribute was set.
   *
   * @return true if the '<code>recentChanges</code>' attribute was set.
   */
  bool has_recent_changes() const {
    return Storage().isMember("recentChanges");
  }

  /**
   * Clears the '<code>recentChanges</code>' attribute.
   */
  void clear_recent_changes() {
    MutableStorage()->removeMember("recentChanges");
  }


  /**
   * Get the value of the '<code>recentChanges</code>' attribute.
   */
  const StringPiece get_recent_changes() const {
    const Json::Value& v = Storage("recentChanges");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>recentChanges</code>' attribute.
   *
   * Describe what's new in your APK.
   *
   * @param[in] value The new value.
   */
  void set_recent_changes(const StringPiece& value) {
    *MutableStorage("recentChanges") = value.data();
  }

 private:
  void operator=(const ApkListing&);
};  // ApkListing
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_APK_LISTING_H_
