// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_APP_DETAILS_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_APP_DETAILS_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class AppDetails : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static AppDetails* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit AppDetails(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit AppDetails(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~AppDetails();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::AppDetails</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::AppDetails");
  }

  /**
   * Determine if the '<code>contactEmail</code>' attribute was set.
   *
   * @return true if the '<code>contactEmail</code>' attribute was set.
   */
  bool has_contact_email() const {
    return Storage().isMember("contactEmail");
  }

  /**
   * Clears the '<code>contactEmail</code>' attribute.
   */
  void clear_contact_email() {
    MutableStorage()->removeMember("contactEmail");
  }


  /**
   * Get the value of the '<code>contactEmail</code>' attribute.
   */
  const StringPiece get_contact_email() const {
    const Json::Value& v = Storage("contactEmail");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>contactEmail</code>' attribute.
   *
   * The user-visible support email for this app.
   *
   * @param[in] value The new value.
   */
  void set_contact_email(const StringPiece& value) {
    *MutableStorage("contactEmail") = value.data();
  }

  /**
   * Determine if the '<code>contactPhone</code>' attribute was set.
   *
   * @return true if the '<code>contactPhone</code>' attribute was set.
   */
  bool has_contact_phone() const {
    return Storage().isMember("contactPhone");
  }

  /**
   * Clears the '<code>contactPhone</code>' attribute.
   */
  void clear_contact_phone() {
    MutableStorage()->removeMember("contactPhone");
  }


  /**
   * Get the value of the '<code>contactPhone</code>' attribute.
   */
  const StringPiece get_contact_phone() const {
    const Json::Value& v = Storage("contactPhone");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>contactPhone</code>' attribute.
   *
   * The user-visible support telephone number for this app.
   *
   * @param[in] value The new value.
   */
  void set_contact_phone(const StringPiece& value) {
    *MutableStorage("contactPhone") = value.data();
  }

  /**
   * Determine if the '<code>contactWebsite</code>' attribute was set.
   *
   * @return true if the '<code>contactWebsite</code>' attribute was set.
   */
  bool has_contact_website() const {
    return Storage().isMember("contactWebsite");
  }

  /**
   * Clears the '<code>contactWebsite</code>' attribute.
   */
  void clear_contact_website() {
    MutableStorage()->removeMember("contactWebsite");
  }


  /**
   * Get the value of the '<code>contactWebsite</code>' attribute.
   */
  const StringPiece get_contact_website() const {
    const Json::Value& v = Storage("contactWebsite");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>contactWebsite</code>' attribute.
   *
   * The user-visible website for this app.
   *
   * @param[in] value The new value.
   */
  void set_contact_website(const StringPiece& value) {
    *MutableStorage("contactWebsite") = value.data();
  }

  /**
   * Determine if the '<code>defaultLanguage</code>' attribute was set.
   *
   * @return true if the '<code>defaultLanguage</code>' attribute was set.
   */
  bool has_default_language() const {
    return Storage().isMember("defaultLanguage");
  }

  /**
   * Clears the '<code>defaultLanguage</code>' attribute.
   */
  void clear_default_language() {
    MutableStorage()->removeMember("defaultLanguage");
  }


  /**
   * Get the value of the '<code>defaultLanguage</code>' attribute.
   */
  const StringPiece get_default_language() const {
    const Json::Value& v = Storage("defaultLanguage");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>defaultLanguage</code>' attribute.
   *
   * Default language code, in BCP 47 format (eg "en-US").
   *
   * @param[in] value The new value.
   */
  void set_default_language(const StringPiece& value) {
    *MutableStorage("defaultLanguage") = value.data();
  }

 private:
  void operator=(const AppDetails&);
};  // AppDetails
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_APP_DETAILS_H_
