// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_COMMENT_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_COMMENT_H_

#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/androidpublisher_api/developer_comment.h"
#include "google/androidpublisher_api/user_comment.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class Comment : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Comment* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Comment(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Comment(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Comment();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::Comment</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::Comment");
  }

  /**
   * Determine if the '<code>developerComment</code>' attribute was set.
   *
   * @return true if the '<code>developerComment</code>' attribute was set.
   */
  bool has_developer_comment() const {
    return Storage().isMember("developerComment");
  }

  /**
   * Clears the '<code>developerComment</code>' attribute.
   */
  void clear_developer_comment() {
    MutableStorage()->removeMember("developerComment");
  }


  /**
   * Get a reference to the value of the '<code>developerComment</code>'
   * attribute.
   */
  const DeveloperComment get_developer_comment() const;

  /**
   * Gets a reference to a mutable value of the '<code>developerComment</code>'
   * property.
   *
   * A comment from a developer.
   *
   * @return The result can be modified to change the attribute value.
   */
  DeveloperComment mutable_developerComment();

  /**
   * Determine if the '<code>userComment</code>' attribute was set.
   *
   * @return true if the '<code>userComment</code>' attribute was set.
   */
  bool has_user_comment() const {
    return Storage().isMember("userComment");
  }

  /**
   * Clears the '<code>userComment</code>' attribute.
   */
  void clear_user_comment() {
    MutableStorage()->removeMember("userComment");
  }


  /**
   * Get a reference to the value of the '<code>userComment</code>' attribute.
   */
  const UserComment get_user_comment() const;

  /**
   * Gets a reference to a mutable value of the '<code>userComment</code>'
   * property.
   *
   * A comment from a user.
   *
   * @return The result can be modified to change the attribute value.
   */
  UserComment mutable_userComment();

 private:
  void operator=(const Comment&);
};  // Comment
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_COMMENT_H_
