// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_ENTITLEMENT_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_ENTITLEMENT_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * An Entitlement resource indicates a user's current entitlement to an inapp
 * item or subscription.
 *
 * @ingroup DataObject
 */
class Entitlement : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Entitlement* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Entitlement(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Entitlement(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Entitlement();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::Entitlement</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::Entitlement");
  }

  /**
   * Determine if the '<code>kind</code>' attribute was set.
   *
   * @return true if the '<code>kind</code>' attribute was set.
   */
  bool has_kind() const {
    return Storage().isMember("kind");
  }

  /**
   * Clears the '<code>kind</code>' attribute.
   */
  void clear_kind() {
    MutableStorage()->removeMember("kind");
  }


  /**
   * Get the value of the '<code>kind</code>' attribute.
   */
  const StringPiece get_kind() const {
    const Json::Value& v = Storage("kind");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>kind</code>' attribute.
   *
   * This kind represents an entitlement object in the androidpublisher service.
   *
   * @param[in] value The new value.
   */
  void set_kind(const StringPiece& value) {
    *MutableStorage("kind") = value.data();
  }

  /**
   * Determine if the '<code>productId</code>' attribute was set.
   *
   * @return true if the '<code>productId</code>' attribute was set.
   */
  bool has_product_id() const {
    return Storage().isMember("productId");
  }

  /**
   * Clears the '<code>productId</code>' attribute.
   */
  void clear_product_id() {
    MutableStorage()->removeMember("productId");
  }


  /**
   * Get the value of the '<code>productId</code>' attribute.
   */
  const StringPiece get_product_id() const {
    const Json::Value& v = Storage("productId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>productId</code>' attribute.
   *
   * The SKU of the product.
   *
   * @param[in] value The new value.
   */
  void set_product_id(const StringPiece& value) {
    *MutableStorage("productId") = value.data();
  }

  /**
   * Determine if the '<code>productType</code>' attribute was set.
   *
   * @return true if the '<code>productType</code>' attribute was set.
   */
  bool has_product_type() const {
    return Storage().isMember("productType");
  }

  /**
   * Clears the '<code>productType</code>' attribute.
   */
  void clear_product_type() {
    MutableStorage()->removeMember("productType");
  }


  /**
   * Get the value of the '<code>productType</code>' attribute.
   */
  const StringPiece get_product_type() const {
    const Json::Value& v = Storage("productType");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>productType</code>' attribute.
   *
   * The type of the inapp product. Possible values are:
   * <dl>
   * <dt>In
   * <dd>app item: "inapp".
   * <dt>Subscription
   * <dd>"subs".
   * </dl>
   *
   *
   * @param[in] value The new value.
   */
  void set_product_type(const StringPiece& value) {
    *MutableStorage("productType") = value.data();
  }

  /**
   * Determine if the '<code>token</code>' attribute was set.
   *
   * @return true if the '<code>token</code>' attribute was set.
   */
  bool has_token() const {
    return Storage().isMember("token");
  }

  /**
   * Clears the '<code>token</code>' attribute.
   */
  void clear_token() {
    MutableStorage()->removeMember("token");
  }


  /**
   * Get the value of the '<code>token</code>' attribute.
   */
  const StringPiece get_token() const {
    const Json::Value& v = Storage("token");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>token</code>' attribute.
   *
   * The token which can be verified using the subscriptions or products API.
   *
   * @param[in] value The new value.
   */
  void set_token(const StringPiece& value) {
    *MutableStorage("token") = value.data();
  }

 private:
  void operator=(const Entitlement&);
};  // Entitlement
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_ENTITLEMENT_H_
