// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_EXTERNALLY_HOSTED_APK_USES_PERMISSION_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_EXTERNALLY_HOSTED_APK_USES_PERMISSION_H_

#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * A permission used by this APK.
 *
 * @ingroup DataObject
 */
class ExternallyHostedApkUsesPermission : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static ExternallyHostedApkUsesPermission* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ExternallyHostedApkUsesPermission(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ExternallyHostedApkUsesPermission(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~ExternallyHostedApkUsesPermission();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return
   * <code>google_androidpublisher_api::ExternallyHostedApkUsesPermission</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::ExternallyHostedApkUsesPermission");
  }

  /**
   * Determine if the '<code>maxSdkVersion</code>' attribute was set.
   *
   * @return true if the '<code>maxSdkVersion</code>' attribute was set.
   */
  bool has_max_sdk_version() const {
    return Storage().isMember("maxSdkVersion");
  }

  /**
   * Clears the '<code>maxSdkVersion</code>' attribute.
   */
  void clear_max_sdk_version() {
    MutableStorage()->removeMember("maxSdkVersion");
  }


  /**
   * Get the value of the '<code>maxSdkVersion</code>' attribute.
   */
  int32 get_max_sdk_version() const {
    const Json::Value& storage = Storage("maxSdkVersion");
    return client::JsonValueToCppValueHelper<int32 >(storage);
  }

  /**
   * Change the '<code>maxSdkVersion</code>' attribute.
   *
   * Optionally, the maximum SDK version for which the permission is required.
   *
   * @param[in] value The new value.
   */
  void set_max_sdk_version(int32 value) {
    client::SetJsonValueFromCppValueHelper<int32 >(
      value, MutableStorage("maxSdkVersion"));
  }

  /**
   * Determine if the '<code>name</code>' attribute was set.
   *
   * @return true if the '<code>name</code>' attribute was set.
   */
  bool has_name() const {
    return Storage().isMember("name");
  }

  /**
   * Clears the '<code>name</code>' attribute.
   */
  void clear_name() {
    MutableStorage()->removeMember("name");
  }


  /**
   * Get the value of the '<code>name</code>' attribute.
   */
  const StringPiece get_name() const {
    const Json::Value& v = Storage("name");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>name</code>' attribute.
   *
   * The name of the permission requested.
   *
   * @param[in] value The new value.
   */
  void set_name(const StringPiece& value) {
    *MutableStorage("name") = value.data();
  }

 private:
  void operator=(const ExternallyHostedApkUsesPermission&);
};  // ExternallyHostedApkUsesPermission
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_EXTERNALLY_HOSTED_APK_USES_PERMISSION_H_
