// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_IMAGE_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_IMAGE_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class Image : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Image* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Image(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Image(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Image();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::Image</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::Image");
  }

  /**
   * Determine if the '<code>id</code>' attribute was set.
   *
   * @return true if the '<code>id</code>' attribute was set.
   */
  bool has_id() const {
    return Storage().isMember("id");
  }

  /**
   * Clears the '<code>id</code>' attribute.
   */
  void clear_id() {
    MutableStorage()->removeMember("id");
  }


  /**
   * Get the value of the '<code>id</code>' attribute.
   */
  const StringPiece get_id() const {
    const Json::Value& v = Storage("id");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>id</code>' attribute.
   *
   * A unique id representing this image.
   *
   * @param[in] value The new value.
   */
  void set_id(const StringPiece& value) {
    *MutableStorage("id") = value.data();
  }

  /**
   * Determine if the '<code>sha1</code>' attribute was set.
   *
   * @return true if the '<code>sha1</code>' attribute was set.
   */
  bool has_sha1() const {
    return Storage().isMember("sha1");
  }

  /**
   * Clears the '<code>sha1</code>' attribute.
   */
  void clear_sha1() {
    MutableStorage()->removeMember("sha1");
  }


  /**
   * Get the value of the '<code>sha1</code>' attribute.
   */
  const StringPiece get_sha1() const {
    const Json::Value& v = Storage("sha1");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>sha1</code>' attribute.
   *
   * A sha1 hash of the image that was uploaded.
   *
   * @param[in] value The new value.
   */
  void set_sha1(const StringPiece& value) {
    *MutableStorage("sha1") = value.data();
  }

  /**
   * Determine if the '<code>url</code>' attribute was set.
   *
   * @return true if the '<code>url</code>' attribute was set.
   */
  bool has_url() const {
    return Storage().isMember("url");
  }

  /**
   * Clears the '<code>url</code>' attribute.
   */
  void clear_url() {
    MutableStorage()->removeMember("url");
  }


  /**
   * Get the value of the '<code>url</code>' attribute.
   */
  const StringPiece get_url() const {
    const Json::Value& v = Storage("url");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>url</code>' attribute.
   *
   * A URL that will serve a preview of the image.
   *
   * @param[in] value The new value.
   */
  void set_url(const StringPiece& value) {
    *MutableStorage("url") = value.data();
  }

 private:
  void operator=(const Image&);
};  // Image
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_IMAGE_H_
