// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Description:
//   Lets Android application developers access their Google Play accounts.
// Classes:
//   InAppProduct
// Documentation:
//   https://developers.google.com/android-publisher

#include "google/androidpublisher_api/in_app_product.h"
#include <string>
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/androidpublisher_api/in_app_product_listing.h"
#include "google/androidpublisher_api/price.h"
#include "google/androidpublisher_api/season.h"


#include <string>
#include "googleapis/strings/strcat.h"

namespace google_androidpublisher_api {
using namespace googleapis;


// Object factory method (static).
InAppProduct* InAppProduct::New() {
  return new client::JsonCppCapsule<InAppProduct>;
}

// Standard immutable constructor.
InAppProduct::InAppProduct(const Json::Value& storage)
  : client::JsonCppData(storage) {
}

// Standard mutable constructor.
InAppProduct::InAppProduct(Json::Value* storage)
  : client::JsonCppData(storage) {
}

// Standard destructor.
InAppProduct::~InAppProduct() {
}

// Properties.

const Price InAppProduct::get_default_price() const {
   const Json::Value& storage = Storage("defaultPrice");
   return client::JsonValueToCppValueHelper<Price >(storage);
}

Price InAppProduct::mutable_defaultPrice() {
  Json::Value* storage = MutableStorage("defaultPrice");
  return client::JsonValueToMutableCppValueHelper<Price >(storage);
}

const client::JsonCppAssociativeArray<InAppProductListing > InAppProduct::get_listings() const {
   const Json::Value& storage = Storage("listings");
   return client::JsonValueToCppValueHelper<client::JsonCppAssociativeArray<InAppProductListing > >(storage);
}

client::JsonCppAssociativeArray<InAppProductListing > InAppProduct::mutable_listings() {
  Json::Value* storage = MutableStorage("listings");
  return client::JsonValueToMutableCppValueHelper<client::JsonCppAssociativeArray<InAppProductListing > >(storage);
}

const client::JsonCppAssociativeArray<Price > InAppProduct::get_prices() const {
   const Json::Value& storage = Storage("prices");
   return client::JsonValueToCppValueHelper<client::JsonCppAssociativeArray<Price > >(storage);
}

client::JsonCppAssociativeArray<Price > InAppProduct::mutable_prices() {
  Json::Value* storage = MutableStorage("prices");
  return client::JsonValueToMutableCppValueHelper<client::JsonCppAssociativeArray<Price > >(storage);
}

const Season InAppProduct::get_season() const {
   const Json::Value& storage = Storage("season");
   return client::JsonValueToCppValueHelper<Season >(storage);
}

Season InAppProduct::mutable_season() {
  Json::Value* storage = MutableStorage("season");
  return client::JsonValueToMutableCppValueHelper<Season >(storage);
}
}  // namespace google_androidpublisher_api
