// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_LISTING_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_LISTING_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class Listing : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Listing* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Listing(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Listing(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Listing();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::Listing</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::Listing");
  }

  /**
   * Determine if the '<code>fullDescription</code>' attribute was set.
   *
   * @return true if the '<code>fullDescription</code>' attribute was set.
   */
  bool has_full_description() const {
    return Storage().isMember("fullDescription");
  }

  /**
   * Clears the '<code>fullDescription</code>' attribute.
   */
  void clear_full_description() {
    MutableStorage()->removeMember("fullDescription");
  }


  /**
   * Get the value of the '<code>fullDescription</code>' attribute.
   */
  const StringPiece get_full_description() const {
    const Json::Value& v = Storage("fullDescription");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>fullDescription</code>' attribute.
   *
   * Full description of the app; this may be up to 4000 characters in length.
   *
   * @param[in] value The new value.
   */
  void set_full_description(const StringPiece& value) {
    *MutableStorage("fullDescription") = value.data();
  }

  /**
   * Determine if the '<code>language</code>' attribute was set.
   *
   * @return true if the '<code>language</code>' attribute was set.
   */
  bool has_language() const {
    return Storage().isMember("language");
  }

  /**
   * Clears the '<code>language</code>' attribute.
   */
  void clear_language() {
    MutableStorage()->removeMember("language");
  }


  /**
   * Get the value of the '<code>language</code>' attribute.
   */
  const StringPiece get_language() const {
    const Json::Value& v = Storage("language");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>language</code>' attribute.
   *
   * Language localization code (for example, "de-AT" for Austrian German).
   *
   * @param[in] value The new value.
   */
  void set_language(const StringPiece& value) {
    *MutableStorage("language") = value.data();
  }

  /**
   * Determine if the '<code>shortDescription</code>' attribute was set.
   *
   * @return true if the '<code>shortDescription</code>' attribute was set.
   */
  bool has_short_description() const {
    return Storage().isMember("shortDescription");
  }

  /**
   * Clears the '<code>shortDescription</code>' attribute.
   */
  void clear_short_description() {
    MutableStorage()->removeMember("shortDescription");
  }


  /**
   * Get the value of the '<code>shortDescription</code>' attribute.
   */
  const StringPiece get_short_description() const {
    const Json::Value& v = Storage("shortDescription");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>shortDescription</code>' attribute.
   *
   * Short description of the app (previously known as promo text); this may be
   * up to 80 characters in length.
   *
   * @param[in] value The new value.
   */
  void set_short_description(const StringPiece& value) {
    *MutableStorage("shortDescription") = value.data();
  }

  /**
   * Determine if the '<code>title</code>' attribute was set.
   *
   * @return true if the '<code>title</code>' attribute was set.
   */
  bool has_title() const {
    return Storage().isMember("title");
  }

  /**
   * Clears the '<code>title</code>' attribute.
   */
  void clear_title() {
    MutableStorage()->removeMember("title");
  }


  /**
   * Get the value of the '<code>title</code>' attribute.
   */
  const StringPiece get_title() const {
    const Json::Value& v = Storage("title");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>title</code>' attribute.
   *
   * App's localized title.
   *
   * @param[in] value The new value.
   */
  void set_title(const StringPiece& value) {
    *MutableStorage("title") = value.data();
  }

  /**
   * Determine if the '<code>video</code>' attribute was set.
   *
   * @return true if the '<code>video</code>' attribute was set.
   */
  bool has_video() const {
    return Storage().isMember("video");
  }

  /**
   * Clears the '<code>video</code>' attribute.
   */
  void clear_video() {
    MutableStorage()->removeMember("video");
  }


  /**
   * Get the value of the '<code>video</code>' attribute.
   */
  const StringPiece get_video() const {
    const Json::Value& v = Storage("video");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>video</code>' attribute.
   *
   * URL of a promotional YouTube video for the app.
   *
   * @param[in] value The new value.
   */
  void set_video(const StringPiece& value) {
    *MutableStorage("video") = value.data();
  }

 private:
  void operator=(const Listing&);
};  // Listing
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_LISTING_H_
