// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_MONTH_DAY_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_MONTH_DAY_H_

#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class MonthDay : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static MonthDay* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit MonthDay(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit MonthDay(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~MonthDay();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::MonthDay</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::MonthDay");
  }

  /**
   * Determine if the '<code>day</code>' attribute was set.
   *
   * @return true if the '<code>day</code>' attribute was set.
   */
  bool has_day() const {
    return Storage().isMember("day");
  }

  /**
   * Clears the '<code>day</code>' attribute.
   */
  void clear_day() {
    MutableStorage()->removeMember("day");
  }


  /**
   * Get the value of the '<code>day</code>' attribute.
   */
  uint32 get_day() const {
    const Json::Value& storage = Storage("day");
    return client::JsonValueToCppValueHelper<uint32 >(storage);
  }

  /**
   * Change the '<code>day</code>' attribute.
   *
   * Day of a month, value in [1, 31] range. Valid range depends on the
   * specified month.
   *
   * @param[in] value The new value.
   */
  void set_day(uint32 value) {
    client::SetJsonValueFromCppValueHelper<uint32 >(
      value, MutableStorage("day"));
  }

  /**
   * Determine if the '<code>month</code>' attribute was set.
   *
   * @return true if the '<code>month</code>' attribute was set.
   */
  bool has_month() const {
    return Storage().isMember("month");
  }

  /**
   * Clears the '<code>month</code>' attribute.
   */
  void clear_month() {
    MutableStorage()->removeMember("month");
  }


  /**
   * Get the value of the '<code>month</code>' attribute.
   */
  uint32 get_month() const {
    const Json::Value& storage = Storage("month");
    return client::JsonValueToCppValueHelper<uint32 >(storage);
  }

  /**
   * Change the '<code>month</code>' attribute.
   *
   * Month of a year. e.g. 1 = JAN, 2 = FEB etc.
   *
   * @param[in] value The new value.
   */
  void set_month(uint32 value) {
    client::SetJsonValueFromCppValueHelper<uint32 >(
      value, MutableStorage("month"));
  }

 private:
  void operator=(const MonthDay&);
};  // MonthDay
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_MONTH_DAY_H_
