// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_PAGE_INFO_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_PAGE_INFO_H_

#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class PageInfo : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static PageInfo* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit PageInfo(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit PageInfo(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~PageInfo();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::PageInfo</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::PageInfo");
  }

  /**
   * Determine if the '<code>resultPerPage</code>' attribute was set.
   *
   * @return true if the '<code>resultPerPage</code>' attribute was set.
   */
  bool has_result_per_page() const {
    return Storage().isMember("resultPerPage");
  }

  /**
   * Clears the '<code>resultPerPage</code>' attribute.
   */
  void clear_result_per_page() {
    MutableStorage()->removeMember("resultPerPage");
  }


  /**
   * Get the value of the '<code>resultPerPage</code>' attribute.
   */
  int32 get_result_per_page() const {
    const Json::Value& storage = Storage("resultPerPage");
    return client::JsonValueToCppValueHelper<int32 >(storage);
  }

  /**
   * Change the '<code>resultPerPage</code>' attribute.
   * @param[in] value The new value.
   */
  void set_result_per_page(int32 value) {
    client::SetJsonValueFromCppValueHelper<int32 >(
      value, MutableStorage("resultPerPage"));
  }

  /**
   * Determine if the '<code>startIndex</code>' attribute was set.
   *
   * @return true if the '<code>startIndex</code>' attribute was set.
   */
  bool has_start_index() const {
    return Storage().isMember("startIndex");
  }

  /**
   * Clears the '<code>startIndex</code>' attribute.
   */
  void clear_start_index() {
    MutableStorage()->removeMember("startIndex");
  }


  /**
   * Get the value of the '<code>startIndex</code>' attribute.
   */
  int32 get_start_index() const {
    const Json::Value& storage = Storage("startIndex");
    return client::JsonValueToCppValueHelper<int32 >(storage);
  }

  /**
   * Change the '<code>startIndex</code>' attribute.
   * @param[in] value The new value.
   */
  void set_start_index(int32 value) {
    client::SetJsonValueFromCppValueHelper<int32 >(
      value, MutableStorage("startIndex"));
  }

  /**
   * Determine if the '<code>totalResults</code>' attribute was set.
   *
   * @return true if the '<code>totalResults</code>' attribute was set.
   */
  bool has_total_results() const {
    return Storage().isMember("totalResults");
  }

  /**
   * Clears the '<code>totalResults</code>' attribute.
   */
  void clear_total_results() {
    MutableStorage()->removeMember("totalResults");
  }


  /**
   * Get the value of the '<code>totalResults</code>' attribute.
   */
  int32 get_total_results() const {
    const Json::Value& storage = Storage("totalResults");
    return client::JsonValueToCppValueHelper<int32 >(storage);
  }

  /**
   * Change the '<code>totalResults</code>' attribute.
   * @param[in] value The new value.
   */
  void set_total_results(int32 value) {
    client::SetJsonValueFromCppValueHelper<int32 >(
      value, MutableStorage("totalResults"));
  }

 private:
  void operator=(const PageInfo&);
};  // PageInfo
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_PAGE_INFO_H_
