// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_PRICE_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_PRICE_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class Price : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Price* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Price(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Price(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Price();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::Price</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::Price");
  }

  /**
   * Determine if the '<code>currency</code>' attribute was set.
   *
   * @return true if the '<code>currency</code>' attribute was set.
   */
  bool has_currency() const {
    return Storage().isMember("currency");
  }

  /**
   * Clears the '<code>currency</code>' attribute.
   */
  void clear_currency() {
    MutableStorage()->removeMember("currency");
  }


  /**
   * Get the value of the '<code>currency</code>' attribute.
   */
  const StringPiece get_currency() const {
    const Json::Value& v = Storage("currency");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>currency</code>' attribute.
   *
   * 3 letter Currency code, as defined by ISO 4217.
   *
   * @param[in] value The new value.
   */
  void set_currency(const StringPiece& value) {
    *MutableStorage("currency") = value.data();
  }

  /**
   * Determine if the '<code>priceMicros</code>' attribute was set.
   *
   * @return true if the '<code>priceMicros</code>' attribute was set.
   */
  bool has_price_micros() const {
    return Storage().isMember("priceMicros");
  }

  /**
   * Clears the '<code>priceMicros</code>' attribute.
   */
  void clear_price_micros() {
    MutableStorage()->removeMember("priceMicros");
  }


  /**
   * Get the value of the '<code>priceMicros</code>' attribute.
   */
  const StringPiece get_price_micros() const {
    const Json::Value& v = Storage("priceMicros");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>priceMicros</code>' attribute.
   *
   * The price in millionths of the currency base unit represented as a string.
   *
   * @param[in] value The new value.
   */
  void set_price_micros(const StringPiece& value) {
    *MutableStorage("priceMicros") = value.data();
  }

 private:
  void operator=(const Price&);
};  // Price
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_PRICE_H_
