// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_REVIEWS_LIST_RESPONSE_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_REVIEWS_LIST_RESPONSE_H_

#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/androidpublisher_api/page_info.h"
#include "google/androidpublisher_api/review.h"
#include "google/androidpublisher_api/token_pagination.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class ReviewsListResponse : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static ReviewsListResponse* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ReviewsListResponse(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ReviewsListResponse(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~ReviewsListResponse();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::ReviewsListResponse</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::ReviewsListResponse");
  }

  /**
   * Determine if the '<code>pageInfo</code>' attribute was set.
   *
   * @return true if the '<code>pageInfo</code>' attribute was set.
   */
  bool has_page_info() const {
    return Storage().isMember("pageInfo");
  }

  /**
   * Clears the '<code>pageInfo</code>' attribute.
   */
  void clear_page_info() {
    MutableStorage()->removeMember("pageInfo");
  }


  /**
   * Get a reference to the value of the '<code>pageInfo</code>' attribute.
   */
  const PageInfo get_page_info() const;

  /**
   * Gets a reference to a mutable value of the '<code>pageInfo</code>'
   * property.
   * @return The result can be modified to change the attribute value.
   */
  PageInfo mutable_pageInfo();

  /**
   * Determine if the '<code>reviews</code>' attribute was set.
   *
   * @return true if the '<code>reviews</code>' attribute was set.
   */
  bool has_reviews() const {
    return Storage().isMember("reviews");
  }

  /**
   * Clears the '<code>reviews</code>' attribute.
   */
  void clear_reviews() {
    MutableStorage()->removeMember("reviews");
  }


  /**
   * Get a reference to the value of the '<code>reviews</code>' attribute.
   */
  const client::JsonCppArray<Review > get_reviews() const;

  /**
   * Gets a reference to a mutable value of the '<code>reviews</code>' property.
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<Review > mutable_reviews();

  /**
   * Determine if the '<code>tokenPagination</code>' attribute was set.
   *
   * @return true if the '<code>tokenPagination</code>' attribute was set.
   */
  bool has_token_pagination() const {
    return Storage().isMember("tokenPagination");
  }

  /**
   * Clears the '<code>tokenPagination</code>' attribute.
   */
  void clear_token_pagination() {
    MutableStorage()->removeMember("tokenPagination");
  }


  /**
   * Get a reference to the value of the '<code>tokenPagination</code>'
   * attribute.
   */
  const TokenPagination get_token_pagination() const;

  /**
   * Gets a reference to a mutable value of the '<code>tokenPagination</code>'
   * property.
   * @return The result can be modified to change the attribute value.
   */
  TokenPagination mutable_tokenPagination();

 private:
  void operator=(const ReviewsListResponse&);
};  // ReviewsListResponse
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_REVIEWS_LIST_RESPONSE_H_
