// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_REVIEW_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_REVIEW_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/androidpublisher_api/comment.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class Review : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Review* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Review(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Review(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Review();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::Review</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::Review");
  }

  /**
   * Determine if the '<code>authorName</code>' attribute was set.
   *
   * @return true if the '<code>authorName</code>' attribute was set.
   */
  bool has_author_name() const {
    return Storage().isMember("authorName");
  }

  /**
   * Clears the '<code>authorName</code>' attribute.
   */
  void clear_author_name() {
    MutableStorage()->removeMember("authorName");
  }


  /**
   * Get the value of the '<code>authorName</code>' attribute.
   */
  const StringPiece get_author_name() const {
    const Json::Value& v = Storage("authorName");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>authorName</code>' attribute.
   *
   * The name of the user who wrote the review.
   *
   * @param[in] value The new value.
   */
  void set_author_name(const StringPiece& value) {
    *MutableStorage("authorName") = value.data();
  }

  /**
   * Determine if the '<code>comments</code>' attribute was set.
   *
   * @return true if the '<code>comments</code>' attribute was set.
   */
  bool has_comments() const {
    return Storage().isMember("comments");
  }

  /**
   * Clears the '<code>comments</code>' attribute.
   */
  void clear_comments() {
    MutableStorage()->removeMember("comments");
  }


  /**
   * Get a reference to the value of the '<code>comments</code>' attribute.
   */
  const client::JsonCppArray<Comment > get_comments() const;

  /**
   * Gets a reference to a mutable value of the '<code>comments</code>'
   * property.
   *
   * A repeated field containing comments for the review.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<Comment > mutable_comments();

  /**
   * Determine if the '<code>reviewId</code>' attribute was set.
   *
   * @return true if the '<code>reviewId</code>' attribute was set.
   */
  bool has_review_id() const {
    return Storage().isMember("reviewId");
  }

  /**
   * Clears the '<code>reviewId</code>' attribute.
   */
  void clear_review_id() {
    MutableStorage()->removeMember("reviewId");
  }


  /**
   * Get the value of the '<code>reviewId</code>' attribute.
   */
  const StringPiece get_review_id() const {
    const Json::Value& v = Storage("reviewId");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>reviewId</code>' attribute.
   *
   * Unique identifier for this review.
   *
   * @param[in] value The new value.
   */
  void set_review_id(const StringPiece& value) {
    *MutableStorage("reviewId") = value.data();
  }

 private:
  void operator=(const Review&);
};  // Review
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_REVIEW_H_
