// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_REVIEWS_REPLY_REQUEST_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_REVIEWS_REPLY_REQUEST_H_

#include <string>
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class ReviewsReplyRequest : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static ReviewsReplyRequest* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ReviewsReplyRequest(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit ReviewsReplyRequest(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~ReviewsReplyRequest();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::ReviewsReplyRequest</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::ReviewsReplyRequest");
  }

  /**
   * Determine if the '<code>replyText</code>' attribute was set.
   *
   * @return true if the '<code>replyText</code>' attribute was set.
   */
  bool has_reply_text() const {
    return Storage().isMember("replyText");
  }

  /**
   * Clears the '<code>replyText</code>' attribute.
   */
  void clear_reply_text() {
    MutableStorage()->removeMember("replyText");
  }


  /**
   * Get the value of the '<code>replyText</code>' attribute.
   */
  const StringPiece get_reply_text() const {
    const Json::Value& v = Storage("replyText");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>replyText</code>' attribute.
   *
   * The text to set as the reply. Replies of more than approximately 350
   * characters will be rejected. HTML tags will be stripped.
   *
   * @param[in] value The new value.
   */
  void set_reply_text(const StringPiece& value) {
    *MutableStorage("replyText") = value.data();
  }

 private:
  void operator=(const ReviewsReplyRequest&);
};  // ReviewsReplyRequest
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_REVIEWS_REPLY_REQUEST_H_
