// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_SEASON_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_SEASON_H_

#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

#include "google/androidpublisher_api/month_day.h"
#include "google/androidpublisher_api/prorate.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class Season : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Season* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Season(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Season(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Season();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::Season</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::Season");
  }

  /**
   * Determine if the '<code>end</code>' attribute was set.
   *
   * @return true if the '<code>end</code>' attribute was set.
   */
  bool has_end() const {
    return Storage().isMember("end");
  }

  /**
   * Clears the '<code>end</code>' attribute.
   */
  void clear_end() {
    MutableStorage()->removeMember("end");
  }


  /**
   * Get a reference to the value of the '<code>end</code>' attribute.
   */
  const MonthDay get_end() const;

  /**
   * Gets a reference to a mutable value of the '<code>end</code>' property.
   *
   * Inclusive end date of the recurrence period.
   *
   * @return The result can be modified to change the attribute value.
   */
  MonthDay mutable_end();

  /**
   * Determine if the '<code>prorations</code>' attribute was set.
   *
   * @return true if the '<code>prorations</code>' attribute was set.
   */
  bool has_prorations() const {
    return Storage().isMember("prorations");
  }

  /**
   * Clears the '<code>prorations</code>' attribute.
   */
  void clear_prorations() {
    MutableStorage()->removeMember("prorations");
  }


  /**
   * Get a reference to the value of the '<code>prorations</code>' attribute.
   */
  const client::JsonCppArray<Prorate > get_prorations() const;

  /**
   * Gets a reference to a mutable value of the '<code>prorations</code>'
   * property.
   *
   * Optionally present list of prorations for the season. Each proration is a
   * one-off discounted entry into a subscription. Each proration contains the
   * first date on which the discount is available and the new pricing
   * information.
   *
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<Prorate > mutable_prorations();

  /**
   * Determine if the '<code>start</code>' attribute was set.
   *
   * @return true if the '<code>start</code>' attribute was set.
   */
  bool has_start() const {
    return Storage().isMember("start");
  }

  /**
   * Clears the '<code>start</code>' attribute.
   */
  void clear_start() {
    MutableStorage()->removeMember("start");
  }


  /**
   * Get a reference to the value of the '<code>start</code>' attribute.
   */
  const MonthDay get_start() const;

  /**
   * Gets a reference to a mutable value of the '<code>start</code>' property.
   *
   * Inclusive start date of the recurrence period.
   *
   * @return The result can be modified to change the attribute value.
   */
  MonthDay mutable_start();

 private:
  void operator=(const Season&);
};  // Season
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_SEASON_H_
