// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_SUBSCRIPTION_DEFERRAL_INFO_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_SUBSCRIPTION_DEFERRAL_INFO_H_

#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * A SubscriptionDeferralInfo contains the data needed to defer a subscription
 * purchase to a future expiry time.
 *
 * @ingroup DataObject
 */
class SubscriptionDeferralInfo : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static SubscriptionDeferralInfo* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit SubscriptionDeferralInfo(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit SubscriptionDeferralInfo(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~SubscriptionDeferralInfo();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::SubscriptionDeferralInfo</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::SubscriptionDeferralInfo");
  }

  /**
   * Determine if the '<code>desiredExpiryTimeMillis</code>' attribute was set.
   *
   * @return true if the '<code>desiredExpiryTimeMillis</code>' attribute was
   * set.
   */
  bool has_desired_expiry_time_millis() const {
    return Storage().isMember("desiredExpiryTimeMillis");
  }

  /**
   * Clears the '<code>desiredExpiryTimeMillis</code>' attribute.
   */
  void clear_desired_expiry_time_millis() {
    MutableStorage()->removeMember("desiredExpiryTimeMillis");
  }


  /**
   * Get the value of the '<code>desiredExpiryTimeMillis</code>' attribute.
   */
  int64 get_desired_expiry_time_millis() const {
    const Json::Value& storage = Storage("desiredExpiryTimeMillis");
    return client::JsonValueToCppValueHelper<int64 >(storage);
  }

  /**
   * Change the '<code>desiredExpiryTimeMillis</code>' attribute.
   *
   * The desired next expiry time to assign to the subscription, in milliseconds
   * since the Epoch. The given time must be later/greater than the current
   * expiry time for the subscription.
   *
   * @param[in] value The new value.
   */
  void set_desired_expiry_time_millis(int64 value) {
    client::SetJsonValueFromCppValueHelper<int64 >(
      value, MutableStorage("desiredExpiryTimeMillis"));
  }

  /**
   * Determine if the '<code>expectedExpiryTimeMillis</code>' attribute was set.
   *
   * @return true if the '<code>expectedExpiryTimeMillis</code>' attribute was
   * set.
   */
  bool has_expected_expiry_time_millis() const {
    return Storage().isMember("expectedExpiryTimeMillis");
  }

  /**
   * Clears the '<code>expectedExpiryTimeMillis</code>' attribute.
   */
  void clear_expected_expiry_time_millis() {
    MutableStorage()->removeMember("expectedExpiryTimeMillis");
  }


  /**
   * Get the value of the '<code>expectedExpiryTimeMillis</code>' attribute.
   */
  int64 get_expected_expiry_time_millis() const {
    const Json::Value& storage = Storage("expectedExpiryTimeMillis");
    return client::JsonValueToCppValueHelper<int64 >(storage);
  }

  /**
   * Change the '<code>expectedExpiryTimeMillis</code>' attribute.
   *
   * The expected expiry time for the subscription. If the current expiry time
   * for the subscription is not the value specified here, the deferral will not
   * occur.
   *
   * @param[in] value The new value.
   */
  void set_expected_expiry_time_millis(int64 value) {
    client::SetJsonValueFromCppValueHelper<int64 >(
      value, MutableStorage("expectedExpiryTimeMillis"));
  }

 private:
  void operator=(const SubscriptionDeferralInfo&);
};  // SubscriptionDeferralInfo
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_SUBSCRIPTION_DEFERRAL_INFO_H_
