// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_TIMESTAMP_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_TIMESTAMP_H_

#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class Timestamp : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Timestamp* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Timestamp(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Timestamp(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Timestamp();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::Timestamp</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::Timestamp");
  }

  /**
   * Determine if the '<code>nanos</code>' attribute was set.
   *
   * @return true if the '<code>nanos</code>' attribute was set.
   */
  bool has_nanos() const {
    return Storage().isMember("nanos");
  }

  /**
   * Clears the '<code>nanos</code>' attribute.
   */
  void clear_nanos() {
    MutableStorage()->removeMember("nanos");
  }


  /**
   * Get the value of the '<code>nanos</code>' attribute.
   */
  int32 get_nanos() const {
    const Json::Value& storage = Storage("nanos");
    return client::JsonValueToCppValueHelper<int32 >(storage);
  }

  /**
   * Change the '<code>nanos</code>' attribute.
   * @param[in] value The new value.
   */
  void set_nanos(int32 value) {
    client::SetJsonValueFromCppValueHelper<int32 >(
      value, MutableStorage("nanos"));
  }

  /**
   * Determine if the '<code>seconds</code>' attribute was set.
   *
   * @return true if the '<code>seconds</code>' attribute was set.
   */
  bool has_seconds() const {
    return Storage().isMember("seconds");
  }

  /**
   * Clears the '<code>seconds</code>' attribute.
   */
  void clear_seconds() {
    MutableStorage()->removeMember("seconds");
  }


  /**
   * Get the value of the '<code>seconds</code>' attribute.
   */
  int64 get_seconds() const {
    const Json::Value& storage = Storage("seconds");
    return client::JsonValueToCppValueHelper<int64 >(storage);
  }

  /**
   * Change the '<code>seconds</code>' attribute.
   * @param[in] value The new value.
   */
  void set_seconds(int64 value) {
    client::SetJsonValueFromCppValueHelper<int64 >(
      value, MutableStorage("seconds"));
  }

 private:
  void operator=(const Timestamp&);
};  // Timestamp
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_TIMESTAMP_H_
