// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_TRACK_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_TRACK_H_

#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * No description provided.
 *
 * @ingroup DataObject
 */
class Track : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static Track* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Track(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit Track(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~Track();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::Track</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::Track");
  }

  /**
   * Determine if the '<code>track</code>' attribute was set.
   *
   * @return true if the '<code>track</code>' attribute was set.
   */
  bool has_track() const {
    return Storage().isMember("track");
  }

  /**
   * Clears the '<code>track</code>' attribute.
   */
  void clear_track() {
    MutableStorage()->removeMember("track");
  }


  /**
   * Get the value of the '<code>track</code>' attribute.
   */
  const StringPiece get_track() const {
    const Json::Value& v = Storage("track");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>track</code>' attribute.
   * @param[in] value The new value.
   */
  void set_track(const StringPiece& value) {
    *MutableStorage("track") = value.data();
  }

  /**
   * Determine if the '<code>userFraction</code>' attribute was set.
   *
   * @return true if the '<code>userFraction</code>' attribute was set.
   */
  bool has_user_fraction() const {
    return Storage().isMember("userFraction");
  }

  /**
   * Clears the '<code>userFraction</code>' attribute.
   */
  void clear_user_fraction() {
    MutableStorage()->removeMember("userFraction");
  }


  /**
   * Get the value of the '<code>userFraction</code>' attribute.
   */
  double get_user_fraction() const {
    const Json::Value& storage = Storage("userFraction");
    return client::JsonValueToCppValueHelper<double >(storage);
  }

  /**
   * Change the '<code>userFraction</code>' attribute.
   * @param[in] value The new value.
   */
  void set_user_fraction(double value) {
    client::SetJsonValueFromCppValueHelper<double >(
      value, MutableStorage("userFraction"));
  }

  /**
   * Determine if the '<code>versionCodes</code>' attribute was set.
   *
   * @return true if the '<code>versionCodes</code>' attribute was set.
   */
  bool has_version_codes() const {
    return Storage().isMember("versionCodes");
  }

  /**
   * Clears the '<code>versionCodes</code>' attribute.
   */
  void clear_version_codes() {
    MutableStorage()->removeMember("versionCodes");
  }


  /**
   * Get a reference to the value of the '<code>versionCodes</code>' attribute.
   */
  const client::JsonCppArray<int32 > get_version_codes() const {
     const Json::Value& storage = Storage("versionCodes");
    return client::JsonValueToCppValueHelper<client::JsonCppArray<int32 > >(storage);
  }

  /**
   * Gets a reference to a mutable value of the '<code>versionCodes</code>'
   * property.
   * @return The result can be modified to change the attribute value.
   */
  client::JsonCppArray<int32 > mutable_versionCodes() {
    Json::Value* storage = MutableStorage("versionCodes");
    return client::JsonValueToMutableCppValueHelper<client::JsonCppArray<int32 > >(storage);
  }

 private:
  void operator=(const Track&);
};  // Track
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_TRACK_H_
