// Copyright 2010 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

// This code was generated by google-apis-code-generator 1.5.1
//   Build date: 2017-02-15 17:18:02 UTC
//   on: 2017-08-09, 13:29:24 UTC
//   C++ generator version: 0.1.4

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   Google Play Developer API (androidpublisher/v2)
// Generated from:
//   Version: v2
//   Revision: 45
// Generated by:
//    Tool: google-apis-code-generator 1.5.1
//     C++: 0.1.4
#ifndef  GOOGLE_ANDROIDPUBLISHER_API_VOIDED_PURCHASE_H_
#define  GOOGLE_ANDROIDPUBLISHER_API_VOIDED_PURCHASE_H_

#include <string>
#include "googleapis/base/integral_types.h"
#include "googleapis/base/macros.h"
#include "googleapis/client/data/jsoncpp_data.h"
#include "googleapis/strings/stringpiece.h"

namespace Json {
class Value;
}  // namespace Json

namespace google_androidpublisher_api {
using namespace googleapis;

/**
 * A VoidedPurchase resource indicates a purchase that was either
 * cancelled/refunded/charged-back.
 *
 * @ingroup DataObject
 */
class VoidedPurchase : public client::JsonCppData {
 public:
  /**
   * Creates a new default instance.
   *
   * @return Ownership is passed back to the caller.
   */
  static VoidedPurchase* New();

  /**
   * Standard constructor for an immutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit VoidedPurchase(const Json::Value& storage);

  /**
   * Standard constructor for a mutable data object instance.
   *
   * @param[in] storage  The underlying data storage for this instance.
   */
  explicit VoidedPurchase(Json::Value* storage);

  /**
   * Standard destructor.
   */
  virtual ~VoidedPurchase();

  /**
   * Returns a string denoting the type of this data object.
   *
   * @return <code>google_androidpublisher_api::VoidedPurchase</code>
   */
  const StringPiece GetTypeName() const {
    return StringPiece("google_androidpublisher_api::VoidedPurchase");
  }

  /**
   * Determine if the '<code>kind</code>' attribute was set.
   *
   * @return true if the '<code>kind</code>' attribute was set.
   */
  bool has_kind() const {
    return Storage().isMember("kind");
  }

  /**
   * Clears the '<code>kind</code>' attribute.
   */
  void clear_kind() {
    MutableStorage()->removeMember("kind");
  }


  /**
   * Get the value of the '<code>kind</code>' attribute.
   */
  const StringPiece get_kind() const {
    const Json::Value& v = Storage("kind");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>kind</code>' attribute.
   *
   * This kind represents a voided purchase object in the androidpublisher
   * service.
   *
   * @param[in] value The new value.
   */
  void set_kind(const StringPiece& value) {
    *MutableStorage("kind") = value.data();
  }

  /**
   * Determine if the '<code>purchaseTimeMillis</code>' attribute was set.
   *
   * @return true if the '<code>purchaseTimeMillis</code>' attribute was set.
   */
  bool has_purchase_time_millis() const {
    return Storage().isMember("purchaseTimeMillis");
  }

  /**
   * Clears the '<code>purchaseTimeMillis</code>' attribute.
   */
  void clear_purchase_time_millis() {
    MutableStorage()->removeMember("purchaseTimeMillis");
  }


  /**
   * Get the value of the '<code>purchaseTimeMillis</code>' attribute.
   */
  int64 get_purchase_time_millis() const {
    const Json::Value& storage = Storage("purchaseTimeMillis");
    return client::JsonValueToCppValueHelper<int64 >(storage);
  }

  /**
   * Change the '<code>purchaseTimeMillis</code>' attribute.
   *
   * The time at which the purchase was made, in milliseconds since the epoch
   * (Jan 1, 1970).
   *
   * @param[in] value The new value.
   */
  void set_purchase_time_millis(int64 value) {
    client::SetJsonValueFromCppValueHelper<int64 >(
      value, MutableStorage("purchaseTimeMillis"));
  }

  /**
   * Determine if the '<code>purchaseToken</code>' attribute was set.
   *
   * @return true if the '<code>purchaseToken</code>' attribute was set.
   */
  bool has_purchase_token() const {
    return Storage().isMember("purchaseToken");
  }

  /**
   * Clears the '<code>purchaseToken</code>' attribute.
   */
  void clear_purchase_token() {
    MutableStorage()->removeMember("purchaseToken");
  }


  /**
   * Get the value of the '<code>purchaseToken</code>' attribute.
   */
  const StringPiece get_purchase_token() const {
    const Json::Value& v = Storage("purchaseToken");
    if (v == Json::Value::null) return StringPiece("");
    return StringPiece(v.asCString());
  }

  /**
   * Change the '<code>purchaseToken</code>' attribute.
   *
   * The token that was generated when a purchase was made. This uniquely
   * identifies a purchase.
   *
   * @param[in] value The new value.
   */
  void set_purchase_token(const StringPiece& value) {
    *MutableStorage("purchaseToken") = value.data();
  }

  /**
   * Determine if the '<code>voidedTimeMillis</code>' attribute was set.
   *
   * @return true if the '<code>voidedTimeMillis</code>' attribute was set.
   */
  bool has_voided_time_millis() const {
    return Storage().isMember("voidedTimeMillis");
  }

  /**
   * Clears the '<code>voidedTimeMillis</code>' attribute.
   */
  void clear_voided_time_millis() {
    MutableStorage()->removeMember("voidedTimeMillis");
  }


  /**
   * Get the value of the '<code>voidedTimeMillis</code>' attribute.
   */
  int64 get_voided_time_millis() const {
    const Json::Value& storage = Storage("voidedTimeMillis");
    return client::JsonValueToCppValueHelper<int64 >(storage);
  }

  /**
   * Change the '<code>voidedTimeMillis</code>' attribute.
   *
   * The time at which the purchase was cancelled/refunded/charged-back, in
   * milliseconds since the epoch (Jan 1, 1970).
   *
   * @param[in] value The new value.
   */
  void set_voided_time_millis(int64 value) {
    client::SetJsonValueFromCppValueHelper<int64 >(
      value, MutableStorage("voidedTimeMillis"));
  }

 private:
  void operator=(const VoidedPurchase&);
};  // VoidedPurchase
}  // namespace google_androidpublisher_api
#endif  // GOOGLE_ANDROIDPUBLISHER_API_VOIDED_PURCHASE_H_
