TARGET = android_publisher
TEMPLATE = lib
CONFIG += staticlib

INCLUDEPATH += \
    $$PWD/../googleapis/include \
    $$PWD/../gflags/include \
    $$PWD/../glog/src \
    $$PWD/../jsoncpp/include

HEADERS += \
    google/androidpublisher_api/android_publisher_service.h \
    google/androidpublisher_api/androidpublisher_api.h \
    google/androidpublisher_api/apk.h \
    google/androidpublisher_api/apk_binary.h \
    google/androidpublisher_api/apk_listing.h \
    google/androidpublisher_api/apk_listings_list_response.h \
    google/androidpublisher_api/apks_add_externally_hosted_request.h \
    google/androidpublisher_api/apks_add_externally_hosted_response.h \
    google/androidpublisher_api/apks_list_response.h \
    google/androidpublisher_api/app_details.h \
    google/androidpublisher_api/app_edit.h \
    google/androidpublisher_api/comment.h \
    google/androidpublisher_api/deobfuscation_file.h \
    google/androidpublisher_api/deobfuscation_files_upload_response.h \
    google/androidpublisher_api/developer_comment.h \
    google/androidpublisher_api/device_metadata.h \
    google/androidpublisher_api/entitlement.h \
    google/androidpublisher_api/entitlements_list_response.h \
    google/androidpublisher_api/expansion_file.h \
    google/androidpublisher_api/expansion_files_upload_response.h \
    google/androidpublisher_api/externally_hosted_apk.h \
    google/androidpublisher_api/externally_hosted_apk_uses_permission.h \
    google/androidpublisher_api/image.h \
    google/androidpublisher_api/images_delete_all_response.h \
    google/androidpublisher_api/images_list_response.h \
    google/androidpublisher_api/images_upload_response.h \
    google/androidpublisher_api/in_app_product.h \
    google/androidpublisher_api/in_app_product_listing.h \
    google/androidpublisher_api/inappproducts_batch_request.h \
    google/androidpublisher_api/inappproducts_batch_request_entry.h \
    google/androidpublisher_api/inappproducts_batch_response.h \
    google/androidpublisher_api/inappproducts_batch_response_entry.h \
    google/androidpublisher_api/inappproducts_insert_request.h \
    google/androidpublisher_api/inappproducts_insert_response.h \
    google/androidpublisher_api/inappproducts_list_response.h \
    google/androidpublisher_api/inappproducts_update_request.h \
    google/androidpublisher_api/inappproducts_update_response.h \
    google/androidpublisher_api/listing.h \
    google/androidpublisher_api/listings_list_response.h \
    google/androidpublisher_api/month_day.h \
    google/androidpublisher_api/page_info.h \
    google/androidpublisher_api/price.h \
    google/androidpublisher_api/product_purchase.h \
    google/androidpublisher_api/prorate.h \
    google/androidpublisher_api/review.h \
    google/androidpublisher_api/review_reply_result.h \
    google/androidpublisher_api/reviews_list_response.h \
    google/androidpublisher_api/reviews_reply_request.h \
    google/androidpublisher_api/reviews_reply_response.h \
    google/androidpublisher_api/season.h \
    google/androidpublisher_api/subscription_deferral_info.h \
    google/androidpublisher_api/subscription_purchase.h \
    google/androidpublisher_api/subscription_purchases_defer_request.h \
    google/androidpublisher_api/subscription_purchases_defer_response.h \
    google/androidpublisher_api/testers.h \
    google/androidpublisher_api/timestamp.h \
    google/androidpublisher_api/token_pagination.h \
    google/androidpublisher_api/track.h \
    google/androidpublisher_api/tracks_list_response.h \
    google/androidpublisher_api/user_comment.h \
    google/androidpublisher_api/voided_purchase.h \
    google/androidpublisher_api/voided_purchases_list_response.h

SOURCES += \
    google/androidpublisher_api/android_publisher_service.cc \
    google/androidpublisher_api/apk.cc \
    google/androidpublisher_api/apk_binary.cc \
    google/androidpublisher_api/apk_listing.cc \
    google/androidpublisher_api/apk_listings_list_response.cc \
    google/androidpublisher_api/apks_add_externally_hosted_request.cc \
    google/androidpublisher_api/apks_add_externally_hosted_response.cc \
    google/androidpublisher_api/apks_list_response.cc \
    google/androidpublisher_api/app_details.cc \
    google/androidpublisher_api/app_edit.cc \
    google/androidpublisher_api/comment.cc \
    google/androidpublisher_api/deobfuscation_file.cc \
    google/androidpublisher_api/deobfuscation_files_upload_response.cc \
    google/androidpublisher_api/developer_comment.cc \
    google/androidpublisher_api/device_metadata.cc \
    google/androidpublisher_api/entitlement.cc \
    google/androidpublisher_api/entitlements_list_response.cc \
    google/androidpublisher_api/expansion_file.cc \
    google/androidpublisher_api/expansion_files_upload_response.cc \
    google/androidpublisher_api/externally_hosted_apk.cc \
    google/androidpublisher_api/externally_hosted_apk_uses_permission.cc \
    google/androidpublisher_api/image.cc \
    google/androidpublisher_api/images_delete_all_response.cc \
    google/androidpublisher_api/images_list_response.cc \
    google/androidpublisher_api/images_upload_response.cc \
    google/androidpublisher_api/in_app_product.cc \
    google/androidpublisher_api/in_app_product_listing.cc \
    google/androidpublisher_api/inappproducts_batch_request.cc \
    google/androidpublisher_api/inappproducts_batch_request_entry.cc \
    google/androidpublisher_api/inappproducts_batch_response.cc \
    google/androidpublisher_api/inappproducts_batch_response_entry.cc \
    google/androidpublisher_api/inappproducts_insert_request.cc \
    google/androidpublisher_api/inappproducts_insert_response.cc \
    google/androidpublisher_api/inappproducts_list_response.cc \
    google/androidpublisher_api/inappproducts_update_request.cc \
    google/androidpublisher_api/inappproducts_update_response.cc \
    google/androidpublisher_api/listing.cc \
    google/androidpublisher_api/listings_list_response.cc \
    google/androidpublisher_api/month_day.cc \
    google/androidpublisher_api/page_info.cc \
    google/androidpublisher_api/price.cc \
    google/androidpublisher_api/product_purchase.cc \
    google/androidpublisher_api/prorate.cc \
    google/androidpublisher_api/review.cc \
    google/androidpublisher_api/review_reply_result.cc \
    google/androidpublisher_api/reviews_list_response.cc \
    google/androidpublisher_api/reviews_reply_request.cc \
    google/androidpublisher_api/reviews_reply_response.cc \
    google/androidpublisher_api/season.cc \
    google/androidpublisher_api/subscription_deferral_info.cc \
    google/androidpublisher_api/subscription_purchase.cc \
    google/androidpublisher_api/subscription_purchases_defer_request.cc \
    google/androidpublisher_api/subscription_purchases_defer_response.cc \
    google/androidpublisher_api/testers.cc \
    google/androidpublisher_api/timestamp.cc \
    google/androidpublisher_api/token_pagination.cc \
    google/androidpublisher_api/track.cc \
    google/androidpublisher_api/tracks_list_response.cc \
    google/androidpublisher_api/user_comment.cc \
    google/androidpublisher_api/voided_purchase.cc \
    google/androidpublisher_api/voided_purchases_list_response.cc
